edit .local/bin/pacman-source

diff --git a/.local/bin/pacman-source b/.local/bin/pacman-source
--- a/.local/bin/pacman-source
+++ b/.local/bin/pacman-source
@@ -11,6 +11,8 @@ if [ "$#" -lt 1 ]; then
 fi
 
 for PKG in "$@"; do
+  pacman -Ss "^$PKG$" &> /dev/null || { echo "Invalid package."; continue; }
+
   rm -rfd "/tmp/$PKG"
 
   git clone --depth 1 --progress "https://gitea.artixlinux.org/packages/$PKG.git" "/tmp/$PKG"
